server:
  port: 8080
spring:
  datasource:
      url: jdbc:mysql://cdb-csnz8qhs.cd.tencentcdb.com:10087/clms?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: code-fusheng
#      url: jdbc:mysql://175.24.45.179/clms_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
#      username: root
#      password: sa123
#      url: jdbc:mysql://127.0.0.1:3306/report?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
#      username: root
#      password: 123456
#      url: jdbc:mysql://127.0.0.1:3306/clms_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
#      username: root
#      password: pengna1314
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 25
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,logback
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  #以下为redis的配置
  redis:
    database: 0  # Redis 数据库索引（默认为 0）
    host: 175.24.45.179 # Redis 服务器地址
    port: 6390 # Redis 服务器连接端口
    password: 123456  # Redis 服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1s  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20  # 连接池中的最大空闲连接
        min-idle: 10  # 连接池中的最小空闲连接
      shutdown-timeout: 5s
  cache:
    type: redis

mybatis:
  configuration:
    map-underscore-to-camel-case: true
github:
  client:
    id: 6ec6304bbb35b05f0194
    secret: c4661c64b6e9a79a887ca694d88b45de9ccdba70
  redirect:
    uri: http://localhost:8080/callback
###################以下为FastDfs的配置###########################
fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 175.24.45.179:22122
upload:
  base-url: http://175.24.45.179/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    - audio/mpeg
